//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVVMApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyMVVMApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contacto y soporte.
        /// </summary>
        public static string AboutInfo_ContactAndSupport {
            get {
                return ResourceManager.GetString("AboutInfo_ContactAndSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acerca de.
        /// </summary>
        public static string AboutInfo_Title {
            get {
                return ResourceManager.GetString("AboutInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to versión.
        /// </summary>
        public static string AboutInfo_Version {
            get {
                return ResourceManager.GetString("AboutInfo_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup/MyMVVMApp.json.
        /// </summary>
        public static string App_BackupFilePath {
            get {
                return ResourceManager.GetString("App_BackupFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyMVVMApp@outlook.com.
        /// </summary>
        public static string App_ContactEmail {
            get {
                return ResourceManager.GetString("App_ContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyMVVMApp.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v1.0.
        /// </summary>
        public static string App_Version {
            get {
                return ResourceManager.GetString("App_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aceptar.
        /// </summary>
        public static string Item_Accept {
            get {
                return ResourceManager.GetString("Item_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancelar.
        /// </summary>
        public static string Item_Cancel {
            get {
                return ResourceManager.GetString("Item_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to descripción.
        /// </summary>
        public static string Item_Description {
            get {
                return ResourceManager.GetString("Item_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombre.
        /// </summary>
        public static string Item_Name {
            get {
                return ResourceManager.GetString("Item_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eliminar.
        /// </summary>
        public static string Item_Remove {
            get {
                return ResourceManager.GetString("Item_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to editar.
        /// </summary>
        public static string Item_TitleEdit {
            get {
                return ResourceManager.GetString("Item_TitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nuevo.
        /// </summary>
        public static string Item_TitleNew {
            get {
                return ResourceManager.GetString("Item_TitleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acerca de.
        /// </summary>
        public static string Main_About {
            get {
                return ResourceManager.GetString("Main_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nuevo.
        /// </summary>
        public static string Main_New {
            get {
                return ResourceManager.GetString("Main_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lista.
        /// </summary>
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemento añadido con éxito.
        /// </summary>
        public static string Message_AddSuccess {
            get {
                return ResourceManager.GetString("Message_AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemento editado con éxito.
        /// </summary>
        public static string Message_EditSuccess {
            get {
                return ResourceManager.GetString("Message_EditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡¡¡Error cargando datos anteriores!!!.
        /// </summary>
        public static string Message_LoadBackupError {
            get {
                return ResourceManager.GetString("Message_LoadBackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemento eliminado con éxito.
        /// </summary>
        public static string Message_RemoveSuccess {
            get {
                return ResourceManager.GetString("Message_RemoveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡¡¡Error guardando los cambios!!!.
        /// </summary>
        public static string Message_SaveBackupError {
            get {
                return ResourceManager.GetString("Message_SaveBackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es-ES.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
